### ISSUE TITLE
Feature: User can 

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/momo-message#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can create an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

the user will be able to register their account by creating a username, email, and password

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![2C1A00B5-843F-4096-8E3A-1D38F6726167](https://github.com/moamel-hashim/momo-message/assets/90476994/26fe1aaf-5689-4e3b-8759-8e23dd33f3a0)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to contain the information for user columns 
- [ ] Update `data.sql` to use the user information

### ☁️ Server Tasks

- [ ] Update `server.js` to communicate between data base and update information
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to handle the registration form. this form would take the information and then send it to the backend 

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented-out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
